sonar.projectKey=Leo-Galli_Aegis-Beacon
sonar.organization=leo-galli

# Project metadata
sonar.projectName=Aegis-Beacon
sonar.sourceEncoding=UTF-8

# Source folders
sonar.sources=src,include

# Ignore build folders
sonar.exclusions=.pio/**,.git/**

# Arduino / C++
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=.cpp,.hpp,.h,.ino

# Optional verbosity
# sonar.verbose=true
