// Single source of truth for wiki navigation: grouped, ordered page ids.
// Titles are resolved from each page's own frontmatter at render time; the
// `label` here is only a fallback short name.
export interface WikiGroup {
  label: string;
  blurb: string;
  pages: { id: string; label: string }[];
}

export const WIKI_NAV: WikiGroup[] = [
  {
    label: 'Onboarding',
    blurb: 'Start from zero: what the beacon is, the basics of radios, Morse and safety, and the learning path.',
    pages: [
      { id: 'onboarding-budget', label: 'Budget Planning' },
      { id: 'onboarding-common-mistakes', label: 'Common Beginner Mistakes' },
      { id: 'onboarding-first-boot', label: 'First Boot' },
      { id: 'onboarding-learning-path', label: 'Learning Path' },
      { id: 'onboarding-legal-basics', label: 'Legal Basics for Beginners' },
      { id: 'onboarding-mission', label: 'How the Beacon Saves Lives' },
      { id: 'onboarding-modes-overview', label: 'Understanding the Modes in One Page' },
      { id: 'onboarding-morse-basics', label: 'Morse Code for Beginners' },
      { id: 'onboarding-parts-overview', label: 'Parts Overview' },
      { id: 'onboarding-reading-oled', label: 'Reading the OLED Screens' },
      { id: 'onboarding-rf-basics', label: 'Radio Basics for Complete Beginners' },
      { id: 'onboarding-safety-first', label: 'Safety First' },
      { id: 'onboarding-tools', label: 'Tools You Need' },
      { id: 'onboarding-using-builder', label: 'Using the BOM Builder' },
      { id: 'onboarding-using-demo', label: 'Using the Interactive Demo' },
      { id: 'onboarding-welcome', label: 'Welcome to the Wiki' },
    ],
  },
  {
    label: 'Getting Started',
    blurb: 'The practical path: parts, flashing, first boot, first transmission, and the FAQ.',
    pages: [
      { id: 'bench-power', label: 'Bench Power' },
      { id: 'bench-testing-basics', label: 'Bench Testing Basics' },
      { id: 'boot-process', label: '"Boot Process"' },
      { id: 'build-configurations', label: '"Build Configurations"' },
      { id: 'choosing-a-build-configuration', label: 'Choosing a Build Configuration' },
      { id: 'esd-safety', label: 'Static Safety and ESD' },
      { id: 'esp32-t-roubleshooting-checklist', label: '"ESP32 Troubleshooting Checklist"' },
      { id: 'faq', label: '"Frequently Asked Questions"' },
      { id: 'first-transmission', label: 'First Transmission' },
      { id: 'first-use', label: '"First Use"' },
      { id: 'project-overview', label: '"Project Overview"' },
      { id: 'quick-start-guide', label: '"Quick Start Guide"' },
      { id: 'shopping-list', label: '"Shopping List"' },
      { id: 'sourcing-parts', label: 'Sourcing Parts' },
      { id: 'system-architecture', label: '"System Architecture"' },
      { id: 'troubleshooting', label: '"Troubleshooting"' },
      { id: 'version-selection', label: 'Version Selection' },
      { id: 'workspace-setup', label: 'Workspace Setup' },
    ],
  },
  {
    label: 'Power & Battery',
    blurb: 'Cells, chargers, regulators, current draw and the math of runtime.',
    pages: [
      { id: '18650-battery-guide', label: '"18650 Battery Guide"' },
      { id: '18650-safety-notes', label: '18650 Safety Notes' },
      { id: 'alternate-power-inputs', label: '"Alternate Power Inputs"' },
      { id: 'battery-capacity-math', label: 'Battery Capacity Math' },
      { id: 'battery-field-swap', label: 'Battery Field Swap' },
      { id: 'battery-monitor-calibration', label: 'Battery Monitor Calibration' },
      { id: 'battery-monitor-details', label: '"Battery Monitor Details"' },
      { id: 'battery-selection', label: '"Battery Selection and Management"' },
      { id: 'battery-storage', label: 'Battery Storage' },
      { id: 'battery-troubleshooting', label: 'Battery Troubleshooting' },
      { id: 'brownout-protection', label: 'Brownout Protection' },
      { id: 'buck-boost-converters', label: 'Buck-Boost Converters' },
      { id: 'cell-chemistry', label: 'Cell Chemistry' },
      { id: 'cell-discharge-curve', label: 'Cell Discharge Curve' },
      { id: 'charger-troubleshooting', label: 'Charger Troubleshooting' },
      { id: 'charging-and-cell-care', label: '"Charging and Cell Care"' },
      { id: 'cold-weather-batteries', label: 'Cold Weather Batteries' },
      { id: 'current-draw-by-mode', label: 'Current Draw by Mode' },
      { id: 'e22-power-levels', label: 'E22 Power Levels' },
      { id: 'esp32-power-input', label: 'ESP32 Power Input' },
      { id: 'first-power-on-protocol', label: 'First Power-On Protocol' },
      { id: 'gps-power-saving', label: 'GPS Power Saving' },
      { id: 'parallel-cells', label: 'Parallel Cells' },
      { id: 'power-budget-and-runtimes', label: '"Power Budget and Runtimes"' },
      { id: 'power-management', label: '"Power Management"' },
      { id: 'power-measurement', label: 'Power Measurement' },
      { id: 'power-quick-reference', label: 'Power Quick Reference' },
      { id: 'protected-vs-unprotected', label: 'Protected vs Unprotected Cells' },
      { id: 'sleep-current', label: 'Sleep Current' },
      { id: 'solar-build', label: 'Solar Build' },
      { id: 'solar-charging', label: 'Solar Charging' },
      { id: 'tp4056-charger-guide', label: '"TP4056 Charger Guide"' },
      { id: 'tp4056-charging-current', label: 'TP4056 Charging Current' },
      { id: 'tp4056-wiring', label: 'TP4056 Wiring' },
      { id: 'undervoltage-protection', label: 'Undervoltage Protection' },
    ],
  },
  {
    label: 'Hardware & Components',
    blurb: 'Every module in the build: the ESP32, radio, OLED, GPS, display and input parts.',
    pages: [
      { id: 'audio-alert-system', label: '"Audio Alert System"' },
      { id: 'audio-tone-details', label: '"Audio Tone Details"' },
      { id: 'board-variants-and-clones', label: '"ESP32 Board Variants"' },
      { id: 'button-types-guide', label: 'Button Types Guide' },
      { id: 'buzzer-types', label: 'Buzzer Types' },
      { id: 'e22-module-pinout', label: 'E22 Module Pinout' },
      { id: 'e22-radio-module-guide', label: '"E22 Radio Module Guide"' },
      { id: 'e22-vs-bare-sx1262', label: 'E22 vs Bare SX1262' },
      { id: 'esp32-board-guide', label: '"ESP32 Board Guide"' },
      { id: 'esp32-board-variants-guide', label: 'ESP32 Board Variants' },
      { id: 'esp32-deep-sleep-hardware', label: 'ESP32 Deep Sleep Hardware' },
      { id: 'esp32-flash-partitions', label: 'ESP32 Flash and Partitions' },
      { id: 'esp32-input-only-pins', label: 'ESP32 Input-Only Pins' },
      { id: 'esp32-sleep-modes', label: '"ESP32 Sleep Modes"' },
      { id: 'esp32-usb-chips', label: 'ESP32 USB Chips' },
      { id: 'firmware-oled-rendering', label: 'Firmware OLED Rendering' },
      { id: 'gps-antenna-types', label: 'GPS Antenna Types' },
      { id: 'gps-module-buying-guide', label: 'GPS Module Buying Guide' },
      { id: 'gps-module-variants', label: '"GPS Module Variants"' },
      { id: 'hardware-components', label: '"Hardware Components"' },
      { id: 'led-status-indicators', label: '"LED Status Indicators"' },
      { id: 'led-wiring', label: 'LED Indicators Wiring' },
      { id: 'neo6m-gps-module-guide', label: '"NEO-6M GPS Module Guide"' },
      { id: 'nx130-gps-module', label: '"NEO-6M GPS Module"' },
      { id: 'nx130-vs-neo-m8n', label: '"NEO-6M vs NEO-M8N"' },
      { id: 'oled-display', label: '"OLED Display"' },
      { id: 'oled-library-notes', label: 'OLED Library Notes' },
      { id: 'oled-panel-guide', label: '"OLED Panel Guide"' },
      { id: 'oled-panel-life', label: 'OLED Panel Life' },
      { id: 'oled-panel-specs', label: 'OLED Panel Specs' },
      { id: 'oled-spi-vs-i2c', label: 'OLED SPI vs I2C' },
      { id: 'radio-library-and-sx1262', label: '"Radio Library and SX1262"' },
      { id: 'radio-module-variants', label: '"Radio Module Variants"' },
    ],
  },
  {
    label: 'Build & Assembly',
    blurb: 'Wiring, soldering, enclosures, sealing and the bench test sequence.',
    pages: [
      { id: '3d-printing-guide', label: '"3D Printing the Enclosure"' },
      { id: 'assembly-guide', label: '"Assembly Guide"' },
      { id: 'assembly-sequence', label: 'Assembly Sequence' },
      { id: 'audio-jack-wiring', label: 'Audio Jack Wiring' },
      { id: 'audio-troubleshooting', label: 'Audio Troubleshooting' },
      { id: 'bench-checklist', label: 'Bench Checklist' },
      { id: 'breadboard-prototyping', label: '"Breadboard Prototyping"' },
      { id: 'building-your-own-case', label: '"Building Your Own Case"' },
      { id: 'button-actions-in-config', label: '"Button Actions in CONFIG Mode"' },
      { id: 'button-system-details', label: '"Button System Details"' },
      { id: 'button-troubleshooting', label: 'Button Troubleshooting' },
      { id: 'case-cutouts-guide', label: 'Case Cutouts Guide' },
      { id: 'case-materials', label: 'Case Materials' },
      { id: 'circuit-description', label: '"Circuit Description"' },
      { id: 'connector-types', label: 'Connector Types' },
      { id: 'datasheet-reading', label: 'Datasheet Reading' },
      { id: 'dummy-load-and-bench-testing', label: '"Dummy Load and Bench Testing"' },
      { id: 'electrical-specifications', label: '"Electrical Specifications"' },
      { id: 'enclosure-options', label: '"Enclosure Options"' },
      { id: 'flux-and-solder', label: 'Flux and Solder' },
      { id: 'glue-and-adhesives', label: 'Glue and Adhesives' },
      { id: 'gpio-pin-map-reference', label: '"GPIO Pin Map Reference"' },
      { id: 'gpio-pin-mapping', label: '"GPIO Pin Mapping"' },
      { id: 'ground-planes-and-counterpoises', label: '"Ground Planes and Counterpoises"' },
      { id: 'ohm-law', label: 'Ohm\'s Law' },
      { id: 'passives-basics', label: 'Resistors, Capacitors and Passives' },
      { id: 'schematic-reading', label: 'Schematic Reading' },
      { id: 'screw-and-fastener-guide', label: 'Screw and Fastener Guide' },
      { id: 'soldering-basics', label: '"Soldering Basics"' },
      { id: 'soldering-iron-guide', label: 'Soldering Iron Guide' },
      { id: 'two-beacon-bench-test', label: '"Two-Beacon Bench Test"' },
      { id: 'waterproof-build', label: 'Waterproof Build' },
      { id: 'waterproofing-and-enclosure-sealing', label: '"Waterproofing and Enclosure Sealing"' },
      { id: 'wire-and-connectors', label: 'Wire and Connectors' },
      { id: 'wire-gauge-guide', label: 'Wire Gauge Guide' },
      { id: 'wiring-and-connectors', label: '"Wiring and Connectors"' },
      { id: 'wiring-order-and-routing', label: 'Wiring Order and Routing' },
      { id: 'wiring-quick-reference', label: 'Wiring Quick Reference' },
    ],
  },
  {
    label: 'Radio & RF Design',
    blurb: 'How the radio works: antennas, propagation, modulation, measurement and link budgets.',
    pages: [
      { id: 'antenna-cable-connectors', label: 'Antenna Cable and Connectors' },
      { id: 'antenna-design', label: '"Antenna Design"' },
      { id: 'antenna-efficiency', label: 'Antenna Efficiency' },
      { id: 'antenna-height-matters', label: 'Antenna Height Matters' },
      { id: 'antenna-lengths', label: '"Antenna Length Reference"' },
      { id: 'antenna-mounting', label: 'Antenna Mounting' },
      { id: 'antenna-quick-select', label: 'Antenna Quick Select' },
      { id: 'antenna-testing-and-tuning', label: '"Antenna Testing and Tuning"' },
      { id: 'antenna-theory-primer', label: 'Antenna Theory Primer' },
      { id: 'antenna-troubleshooting', label: 'Antenna Troubleshooting' },
      { id: 'antenna-types', label: '"Antenna Design and Selection"' },
      { id: 'coax-loss-tables', label: 'Coax Loss Tables' },
      { id: 'dbm-explained', label: 'dBm Explained' },
      { id: 'foliage-loss', label: 'Foliage Loss' },
      { id: 'fresnel-zone', label: 'The Fresnel Zone' },
      { id: 'gps-antenna-placement', label: '"GPS Antenna Placement"' },
      { id: 'half-wave-dipole', label: 'Half Wave Dipole' },
      { id: 'helical-antenna', label: 'Helical Antenna' },
      { id: 'homebrew-antenna', label: 'Homebrew Antenna' },
      { id: 'interference-sources', label: 'Interference Sources at 433 MHz' },
      { id: 'line-of-sight-terrain', label: 'Line of Sight and Terrain' },
      { id: 'lora-vs-fsk', label: 'LoRa vs FSK' },
      { id: 'modulation-in-the-beacon', label: '"Modulation in the Beacon"' },
      { id: 'morse-antenna-and-tone-relationship', label: '"Morse Timing and Audio Sync"' },
      { id: 'mountain-effects-radio', label: 'Mountain Effects on Radio' },
      { id: 'propagation-and-range', label: '"Propagation and Range"' },
      { id: 'propagation-modes', label: 'Propagation Modes' },
      { id: 'quarter-wave-antenna', label: 'Quarter Wave Antenna' },
      { id: 'radio-quick-start', label: 'Radio Quick Start' },
      { id: 'radio-shadow', label: 'Radio Shadow' },
      { id: 'receiver-testing', label: 'Receiver Testing' },
      { id: 'rf-basics', label: '"RF Basics for the Beacon"' },
      { id: 'rf-design-link-budget', label: '"RF Design & Link Budget"' },
      { id: 'rf-exposure-safety', label: '"RF Exposure Safety"' },
      { id: 'rf-interference-and-noise', label: '"RF Interference and Noise"' },
      { id: 'rssi-explained', label: 'RSSI Explained' },
      { id: 'sensitivity-vs-selectivity', label: 'Sensitivity vs Selectivity' },
      { id: 'swr-explained', label: 'SWR Explained' },
      { id: 'sx1262-datasheet-notes', label: '"SX1262 Datasheet Notes"' },
      { id: 'sx1262-frequency-ranges', label: 'SX1262 Frequency Ranges' },
      { id: 'sx1262-registers', label: 'SX1262 Registers' },
      { id: 'transmitter-testing', label: 'Transmitter Testing' },
      { id: 'tropospheric-ducting', label: 'Tropospheric Ducting' },
      { id: 'troubleshooting-rf', label: '"Troubleshooting RF Issues"' },
      { id: 'urban-rf-environment', label: 'Urban RF Environment' },
      { id: 'vswr-measurement', label: 'VSWR Measurement' },
    ],
  },
  {
    label: 'Frequencies & Regulations',
    blurb: 'The 433 MHz band, legal frameworks by country, licensing, and the emergency exception.',
    pages: [
      { id: '70cm-band', label: 'The 70 cm Amateur Band' },
      { id: 'amateur-license-process', label: 'Amateur License Process' },
      { id: 'austria-radio-legal', label: 'Austria Radio Legal' },
      { id: 'callsign-identification', label: 'Callsign Identification' },
      { id: 'duty-cycle-rule', label: 'Duty Cycle Rules' },
      { id: 'emergency-frequencies', label: 'Emergency Frequencies' },
      { id: 'emergency-use-legal', label: 'Emergency Use Legal' },
      { id: 'erp-vs-eirp', label: 'ERP vs EIRP' },
      { id: 'france-radio-legal', label: 'France Radio Legal' },
      { id: 'frequency-compatibility', label: '"Frequency Compatibility"' },
      { id: 'frequency-planning-examples', label: '"Frequency Planning Examples"' },
      { id: 'frequency-table-reference', label: 'Frequency Table Reference' },
      { id: 'germany-radio-legal', label: 'Germany Radio Legal' },
      { id: 'ism-band-explained', label: 'ISM Bands Explained' },
      { id: 'italy-radio-legal', label: 'Italy Radio Legal' },
      { id: 'license-classes', label: 'License Classes' },
      { id: 'pmr446-deep-dive', label: 'PMR446 Deep Dive' },
      { id: 'regulatory-compliance', label: '"Regulatory Compliance"' },
      { id: 'safety-and-liability', label: '"Safety and Liability"' },
      { id: 'scanning-frequency-table', label: 'Scanning the Band' },
      { id: 'switzerland-radio-legal', label: 'Switzerland Radio Legal' },
      { id: 'uk-radio-legal', label: 'UK Radio Legal' },
      { id: 'us-radio-legal', label: 'US Radio Legal' },
    ],
  },
  {
    label: 'Firmware & Software',
    blurb: 'The firmware architecture, configuration, build tools, serial debugging and the dashboard.',
    pages: [
      { id: 'arduino-cli-guide', label: 'Arduino CLI Guide' },
      { id: 'boot-loop-troubleshooting', label: 'Boot Loop Troubleshooting' },
      { id: 'boot-screens-and-errors', label: '"Boot Screens and Errors"' },
      { id: 'changelog', label: '"Changelog"' },
      { id: 'code-style-guide', label: 'Code Style Guide' },
      { id: 'config-backup', label: 'Config Backup' },
      { id: 'config-dashboard', label: 'Config Dashboard' },
      { id: 'config-dashboard-offline-fonts', label: 'Why the Dashboard Uses System Fonts' },
      { id: 'config-payload-format', label: '"CONFIG Payload Format"' },
      { id: 'configuration-reference', label: '"Configuration Reference"' },
      { id: 'dashboard-http-api', label: '"Dashboard HTTP API"' },
      { id: 'dashboard-rendering', label: '"Dashboard Rendering"' },
      { id: 'esp32-adc-guide', label: 'ESP32 ADC Guide' },
      { id: 'esp32-flash-security', label: 'ESP32 Flash Security' },
      { id: 'esp32-interrupts-guide', label: 'ESP32 Interrupts Guide' },
      { id: 'esp32-rtc-notes', label: 'ESP32 RTC Notes' },
      { id: 'esp32-serial-debug', label: '"ESP32 Serial Debug Output"' },
      { id: 'esp32-timers-guide', label: 'ESP32 Timers Guide' },
      { id: 'esp32-wifi-hardware', label: 'ESP32 WiFi Hardware' },
      { id: 'esptool-guide', label: 'esptool Guide' },
      { id: 'extending-serial-protocol', label: 'Extending the Serial Protocol' },
      { id: 'factory-reset-and-recovery', label: '"Factory Reset and Recovery"' },
      { id: 'firmware-cw-decoder', label: 'Firmware CW Decoder' },
      { id: 'firmware-system-monitoring', label: 'Firmware System Monitoring' },
      { id: 'frequency-setting-over-serial', label: 'Frequency Setting over Serial' },
      { id: 'firmware-buttons', label: 'The Button System in Firmware' },
      { id: 'firmware-config-load', label: 'How Firmware Loads Configuration' },
      { id: 'firmware-deep-sleep', label: 'Firmware Deep Sleep' },
      { id: 'firmware-error-codes', label: 'Firmware Error Codes' },
      { id: 'firmware-gps-handling', label: 'Firmware GPS Handling' },
      { id: 'firmware-main-loop', label: 'The Firmware Main Loop' },
      { id: 'firmware-nvs-keys', label: 'Firmware NVS Keys' },
      { id: 'firmware-overview', label: '"Firmware Overview"' },
      { id: 'firmware-payload-builder', label: 'The Payload Builder' },
      { id: 'firmware-rssi-measurement', label: 'Firmware RSSI Measurement' },
      { id: 'firmware-scan-cycle', label: 'The Scan Cycle in Detail' },
      { id: 'firmware-scan-engine', label: 'Firmware Scan Engine' },
      { id: 'firmware-state-machine', label: 'The Firmware State Machine' },
      { id: 'firmware-tone-generation', label: 'Firmware Tone Generation' },
      { id: 'firmware-tx-cycle', label: 'The TX Cycle in Detail' },
      { id: 'firmware-tx-scheduler', label: 'Firmware TX Scheduler' },
      { id: 'firmware-v55-upgrade-guide', label: 'Upgrading to v5.5' },
      { id: 'firmware-update-field', label: 'Firmware Update in the Field' },
      { id: 'firmware-wake-sources', label: 'Firmware Wake Sources' },
      { id: 'firmware-watchdog', label: 'The Watchdog' },
      { id: 'flash-troubleshooting', label: 'Flash Troubleshooting' },
      { id: 'no-boot-troubleshooting', label: 'No Boot? Troubleshooting' },
      { id: 'no-display-troubleshooting', label: 'No Display? Troubleshooting' },
      { id: 'nvs-configuration-store', label: '"NVS Configuration Store"' },
      { id: 'platformio-guide', label: 'PlatformIO Guide' },
      { id: 'rtc-ram-state', label: '"RTC RAM State"' },
      { id: 'serial-battery-logging', label: 'Battery Logging over Serial' },
      { id: 'serial-bridge-guide', label: 'Serial Bridge Guide' },
      { id: 'serial-command-automation', label: 'Serial Command Automation' },
      { id: 'serial-command-protocol', label: 'Serial Command Protocol' },
      { id: 'serial-debug-system', label: '"Serial Debug System"' },
      { id: 'serial-monitor-guide', label: 'Serial Monitor Guide' },
      { id: 'software-build-process', label: '"Software Build Process"' },
      { id: 'unit-testing-firmware', label: 'Unit Testing the Firmware' },
      { id: 'upload-and-monitor', label: '"Upload and Monitor"' },
      { id: 'whats-new-v55', label: 'What\'s New in v5.5' },
      { id: 'whats-new-v60', label: 'What\'s New in v6.0' },
      { id: 'wifi-and-security', label: '"WiFi and Security"' },
      { id: 'wifi-config-portal', label: '"WiFi Configuration Portal"' },
      { id: 'wifi-troubleshooting', label: 'WiFi Troubleshooting' },
    ],
  },
  {
    label: 'USB & Connectivity',
    blurb: 'Connecting the beacon over USB: cables, drivers, ports, phones, and the serial bridge that reports positions.',
    pages: [
      { id: 'android-otg-guide', label: 'Android OTG Guide' },
      { id: 'bridge-automation', label: 'Bridge Automation' },
      { id: 'bridge-security', label: 'Bridge Security' },
      { id: 'bridge-troubleshooting', label: 'Bridge Troubleshooting' },
      { id: 'bridge-tui', label: 'Bridge TUI' },
      { id: 'ch340-driver-install', label: 'CH340 Driver Install' },
      { id: 'cp210x-driver-install', label: 'CP210x Driver Install' },
      { id: 'report-position-page', label: 'Report Position Page' },
      { id: 'serial-adapter-troubleshooting', label: 'USB-Serial Adapter Troubleshooting' },
      { id: 'serial-port-detection', label: 'Serial Port Detection' },
      { id: 'termux-serial-bridge', label: 'Termux Serial Bridge' },
      { id: 'usb-cable-types', label: 'USB Cable Types' },
      { id: 'usb-connection-guide', label: 'USB Connection Guide' },
      { id: 'usb-power-and-data', label: 'USB Power vs Data' },
      { id: 'web-serial-browser-support', label: 'Web Serial Browser Support' },
    ],
  },
  {
    label: 'GPS & Navigation',
    blurb: 'The GPS module, NMEA data, coordinate formats, fix quality and navigation skills.',
    pages: [
      { id: 'coordinate-conversion', label: 'Coordinate Conversion' },
      { id: 'coordinate-plotting-and-maps', label: '"Coordinate Plotting and Maps"' },
      { id: 'gps-build-configuration', label: 'GPS Build Configuration' },
      { id: 'gps-coordinate-accuracy', label: '"GPS Coordinate Accuracy"' },
      { id: 'gps-coordinate-systems', label: 'GPS Coordinate Systems' },
      { id: 'gps-failure-contingency', label: 'GPS Failure Contingency' },
      { id: 'gps-fix-capture-tips', label: 'GPS Fix Capture Tips' },
      { id: 'gps-fix-quality', label: 'GPS Fix Quality' },
      { id: 'gps-integration', label: '"GPS Integration"' },
      { id: 'gps-nmea-sentences', label: 'GPS NMEA Sentences' },
      { id: 'gps-quick-fix', label: 'GPS Quick Fix' },
      { id: 'gps-satellite-count', label: 'GPS Satellite Count' },
      { id: 'gps-sky-view', label: 'GPS Sky View' },
      { id: 'gps-testing-indoors', label: 'GPS Testing Indoors' },
      { id: 'gps-timing', label: 'GPS Timing' },
      { id: 'gps-troubleshooting', label: '"GPS Troubleshooting"' },
      { id: 'gps-utm-vs-decimal', label: 'GPS UTM vs Decimal' },
      { id: 'gps-warm-vs-cold-start', label: 'GPS Warm vs Cold Start' },
      { id: 'position-reporting', label: 'Position Reporting' },
      { id: 'ublox-uart-config', label: 'Configuring the NEO-6M over UART' },
    ],
  },
  {
    label: 'Morse & Communication',
    blurb: 'Morse code, decoders, phonetics, Q codes, radio etiquette and receiving the signal.',
    pages: [
      { id: 'audio-recording-guide', label: 'Audio Recording Guide' },
      { id: 'band-plan-etiquette', label: 'Band Plan Etiquette' },
      { id: 'decibel-table', label: 'Decibel Table' },
      { id: 'mayday-vs-panpan', label: 'Mayday vs Pan Pan' },
      { id: 'morse-abbreviations-and-prosigns', label: '"Morse Abbreviations and Prosigns"' },
      { id: 'morse-audio-cheat-sheet', label: 'Morse Audio Cheat Sheet' },
      { id: 'morse-code-engine', label: '"Morse Code Engine"' },
      { id: 'morse-code-learning-apps', label: 'Morse Code Learning Apps' },
      { id: 'morse-decoder-tools', label: '"Morse Decoder Tools"' },
      { id: 'morse-history-and-background', label: '"Morse Code Background"' },
      { id: 'morse-keying-practice', label: 'Morse Keying Practice' },
      { id: 'morse-listening-workflow', label: 'Morse Listening Workflow' },
      { id: 'morse-letter-table', label: 'Morse Letter Table' },
      { id: 'morse-numbers-punctuation', label: 'Morse Numbers and Punctuation' },
      { id: 'morse-practice', label: '"Morse Practice"' },
      { id: 'morse-timing-reference', label: '"Morse Timing Reference"' },
      { id: 'payload-examples', label: 'Payload Examples' },
      { id: 'phonetics', label: 'Phonetics' },
      { id: 'q-codes', label: 'Q Codes' },
      { id: 'radio-communication-basics', label: '"Radio Communication Basics"' },
      { id: 'radio-etiquette-basics', label: 'Radio Etiquette Basics' },
      { id: 'reading-cw-by-ear', label: '"Reading CW by Ear"' },
      { id: 'receiver-compatibility', label: '"Receiver Compatibility"' },
      { id: 'rescue-communication-basics', label: 'Rescue Communication Basics' },
      { id: 'sdr-beacon-build', label: 'SDR Beacon Build' },
      { id: 'sdr-decoding-morse', label: 'SDR Decoding Morse' },
      { id: 'sdr-listening-guide', label: '"SDR Listening Guide"' },
      { id: 'sdr-software-setup', label: 'SDR Software Setup' },
      { id: 'signal-reporting-conventions', label: '"Signal Reporting Conventions"' },
      { id: 'simplex-communication', label: 'Simplex Communication' },
      { id: 'spectrum-analyzers', label: 'Spectrum Analyzers' },
      { id: 'two-way-build', label: 'Two-Way Build' },
    ],
  },
  {
    label: 'Modes & Operation',
    blurb: 'The operating modes, screens, buttons and the scan engine.',
    pages: [
      { id: 'glossary-modes-and-settings', label: '"Glossary of Modes and Settings"' },
      { id: 'mode-beacon', label: '"BEACON Mode"' },
      { id: 'mode-config', label: '"CONFIG Mode"' },
      { id: 'mode-emergency', label: '"EMERGENCY Mode"' },
      { id: 'mode-listen', label: '"LISTEN Mode"' },
      { id: 'mode-search', label: '"SEARCH Mode"' },
      { id: 'operating-modes-oled', label: '"Mode Screens and Icons"' },
      { id: 'operating-modes', label: '"Operating Modes"' },
      { id: 'scan-engine-details', label: '"Scan Engine Details"' },
    ],
  },
  {
    label: 'Field Operations & Rescue',
    blurb: 'The field playbook: deployment, search, signaling, emergencies, winter and the checklists.',
    pages: [
      { id: 'avalanche-rescue-operation', label: '"Avalanche Rescue Operation"' },
      { id: 'avalanche-safety-basics', label: 'Avalanche Safety Basics' },
      { id: 'beacon-care-seasonal', label: 'Beacon Care Seasonal' },
      { id: 'beacon-log-template', label: 'Beacon Log Template' },
      { id: 'cleaning-and-inspection', label: 'Cleaning and Inspection' },
      { id: 'crevasse-rescue', label: 'Crevasse Rescue' },
      { id: 'distance-estimation-rssi', label: 'Distance Estimation from RSSI' },
      { id: 'emergency-cheat-sheet', label: 'Emergency Cheat Sheet' },
      { id: 'emergency-communications-plan', label: '"Emergency Communications Plan"' },
      { id: 'emergency-kit', label: 'Emergency Kit' },
      { id: 'emergency-response-minute-by-minute', label: 'Emergency Response Minute by Minute' },
      { id: 'emergency-response-scenarios', label: '"Emergency Response Scenarios"' },
      { id: 'field-checklist', label: 'Field Checklist' },
      { id: 'field-deployment', label: '"Field Deployment Guide"' },
      { id: 'field-maintenance-and-storage', label: '"Field Maintenance and Storage"' },
      { id: 'field-repair-kit', label: 'Field Repair Kit' },
      { id: 'field-signals-cheat-sheet', label: 'Field Signals Cheat Sheet' },
      { id: 'first-aid-kit', label: 'First Aid Kit' },
      { id: 'ground-to-air-signals', label: 'Ground to Air Signals' },
      { id: 'group-communication-plan', label: 'Group Communication Plan' },
      { id: 'hiking-safety', label: 'Hiking Safety' },
      { id: 'homing-technique', label: 'Homing Technique' },
      { id: 'homing-with-bridge', label: 'Homing with the Serial Bridge' },
      { id: 'hypothermia-recognition', label: 'Hypothermia Recognition' },
      { id: 'incident-command', label: 'Incident Command' },
      { id: 'long-term-storage', label: 'Long Term Storage' },
      { id: 'mirror-signaling', label: 'Mirror Signaling' },
      { id: 'mission-debrief', label: 'Mission Debrief' },
      { id: 'multi-device-bridge', label: 'One Bridge, Several Beacons' },
      { id: 'night-operations', label: 'Night Operations' },
      { id: 'off-grid-position-sharing', label: 'Off-Grid Position Sharing' },
      { id: 'outdoor-testing', label: '"Outdoor Testing Guide"' },
      { id: 'pack-check-routine', label: 'Pack Check Routine' },
      { id: 'position-logging-workflow', label: 'Position Logging Workflow' },
      { id: 'pre-trip-checklist', label: '"Pre-Trip Checklist"' },
      { id: 'repeater-position-reporting', label: 'Repeater Position Reporting' },
      { id: 'ridge-crossing-technique', label: 'Ridge Crossing Technique' },
      { id: 'safety-guidelines', label: '"Safety Guidelines"' },
      { id: 'safety-quick-rules', label: 'Safety Quick Rules' },
      { id: 'search-patterns-and-procedure', label: '"Search Patterns and Procedure"' },
      { id: 'signal-strength-mapping', label: 'Signal Strength Mapping' },
      { id: 'signal-triangulation', label: 'Signal Triangulation' },
      { id: 'signaling-techniques', label: 'Signaling Techniques' },
      { id: 'snow-and-signal-behavior', label: '"Snow and Signal Behavior"' },
      { id: 'snow-shelter-signaling', label: 'Snow Shelter Signaling' },
      { id: 'snow-signal-math', label: 'Snow Signal Math' },
      { id: 'storm-operations', label: 'Storm Operations' },
      { id: 'terrain-reading-for-radio', label: 'Terrain Reading for Radio' },
      { id: 'trip-planning', label: 'Trip Planning' },
      { id: 'water-damage-recovery', label: 'Water Damage Recovery' },
      { id: 'weather-planning', label: 'Weather Planning' },
      { id: 'whistle-signals', label: 'Whistle Signals' },
      { id: 'winter-operations', label: '"Winter Operations"' },
      { id: 'winter-pack', label: 'Winter Pack' },
    ],
  },
  {
    label: 'Building Effectively',
    blurb: 'How to plan, execute and log a build so it works the first time: stage order, quality gates, fixtures, rework and time planning.',
    pages: [
      { id: 'effective-build-strategy', label: 'Effective Build Strategy' },
      { id: 'build-quality-gates', label: 'Build Quality Gates' },
      { id: 'bench-jigs-and-fixtures', label: 'Bench Jigs and Fixtures' },
      { id: 'rework-and-desoldering', label: 'Rework and Desoldering' },
      { id: 'build-time-planning', label: 'Build Time Planning' },
      { id: 'build-log-and-tracking', label: 'Build Log and Tracking' },
    ],
  },
  {
    label: 'Build Variants',
    blurb: 'Alternative builds and multi-beacon setups: minimal, displayless, GPS-focused, solar and more.',
    pages: [
      { id: 'displayless-build', label: 'Displayless Build' },
      { id: 'minimal-build', label: 'Minimal Build' },
      { id: 'multi-beacon-network', label: 'Multi-Beacon Network' },
      { id: 'multi-beacon-operations', label: '"Multi-Beacon Operations"' },
      { id: 'multi-beacon-planning', label: 'Multi-Beacon Frequency Planning' },
      { id: 'repeater-beacon', label: 'Repeater Beacon' },
      { id: 'standard-build-configuration', label: 'Standard Build Configuration' },
    ],
  },
  {
    label: 'Project & Reference',
    blurb: 'The project itself: history, roadmap, contributing, releases, SEO and the quick references.',
    pages: [
      { id: 'acknowledgements', label: 'Acknowledgements' },
      { id: 'attribution-and-license', label: '"Attribution and License"' },
      { id: 'benchmark-methodology', label: 'Benchmark Methodology' },
      { id: 'beacon-settings-reference', label: 'Beacon Settings Reference' },
      { id: 'branding', label: 'Branding' },
      { id: 'ci-cd', label: 'CI/CD' },
      { id: 'commercial-plb-vs-diy', label: 'Commercial PLB vs DIY' },
      { id: 'community-resources', label: 'Community Resources' },
      { id: 'comparison-with-alternatives', label: '"Comparison with Alternatives"' },
      { id: 'configuration-quick-guide', label: 'Configuration Quick Guide' },
      { id: 'contact-and-support', label: 'Contact and Support' },
      { id: 'contributing', label: '"Contributing to Aegis-Beacon"' },
      { id: 'deployment', label: 'Deployment' },
      { id: 'feature-requests', label: 'Feature Requests' },
      { id: 'git-basics', label: 'Git Basics' },
      { id: 'github-workflow-guide', label: 'GitHub Workflow Guide' },
      { id: 'glossary', label: '"Glossary"' },
      { id: 'project-history', label: 'Project History' },
      { id: 'quick-reference-sheet', label: 'Quick Reference Sheet' },
      { id: 'release-process', label: 'Release Process' },
      { id: 'reliability-and-safety-features', label: '"Reliability & Safety Features"' },
      { id: 'reporting-issues', label: 'Reporting Issues' },
      { id: 'roadmap', label: 'Roadmap' },
      { id: 'robots-and-sitemap', label: 'Robots and Sitemap' },
      { id: 'seo', label: 'SEO' },
      { id: 'test-procedures-overview', label: 'Test Procedures Overview' },
      { id: 'translations', label: 'Translations' },
      { id: 'unit-conversions', label: 'Unit Conversions' },
      { id: 'why-433mhz', label: 'Why 433 MHz' },
    ],
  },
];

/** Flat ordered list of every wiki page id. */
export const WIKI_FLAT: string[] = WIKI_NAV.flatMap((g) => g.pages.map((p) => p.id));

/** Look up which group a page belongs to. */
export function groupForPage(id: string): WikiGroup | undefined {
  return WIKI_NAV.find((g) => g.pages.some((p) => p.id === id));
}

/** Resolve a page's fallback short label. */
export function labelForPage(id: string): string {
  for (const g of WIKI_NAV) {
    const p = g.pages.find((p) => p.id === id);
    if (p) return p.label;
  }
  return id;
}
